server:
    # 端口号 
    port: 6232

cnyiot:
    username: 19xxxxxxxxx
    password: xxxxxx
    key: xxxxx

forest:
    max-connections: 1000        # 连接池最大连接数
    connect-timeout: 3000        # 连接超时时间，单位为毫秒
    read-timeout: 3000           # 数据读取超时时间，单位为毫秒
    log-enabled: true            # 打开或关闭日志（默认为 true）
    log-request: true            # 打开/关闭Forest请求日志（默认为 true）
    log-response-status: true    # 打开/关闭Forest响应状态日志（默认为 true）
    log-response-content: true   # 打开/关闭Forest响应内容日志（默认为 false）
    max-retry-count: 1           # 重试次数1次